services:
  - type: web
    name: real-estate-website
    env: static
    buildCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 